[package]
name = "ruster_unsafe_demo"
version = "0.0.1"
authors = ["Daniel Goertzen <daniel.goertzen@gmail.com>"]

[lib]
name = "ruster_unsafe_demo"
crate-type = ["dylib"]

[dependencies]
ruster_unsafe = "0.1"
