[package]
name = "ruster_unsafe_demo"
version = "0.0.2"
authors = ["Daniel Goertzen <daniel.goertzen@gmail.com>"]

[lib]
name = "ruster_unsafe_demo"
crate-type = ["dylib"]

[dependencies]
#ruster_unsafe = "0.4.0"
ruster_unsafe = { path = "/home/goertzen/ruster_unsafe" }
